Craiglist_WebScraping/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('my_app.urls')),
    path('admin/', admin.site.urls),
]

my_app/urls.py
from django.urls import path
from . import views

app_name = "my_app"
urlpatterns = [
    path('', views.home, name="home"),
    path("new_search", views.new_search, name="new_search")
]

my_app/models.py
from django.db import models

# Create your models here.
class Search(models.Model):
    search = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.search

    class Meta:
        verbose_name_plural = "Searches"

my_app/views.py
from django.shortcuts import render
import re
from bs4 import BeautifulSoup 
import requests
from requests.compat import quote_plus
from . import models

BASE_CRAIGLIST_URL = 'https://london.craigslist.org/search/sss?query={}'
BASE_CRAIGLIST_IMAGE_URL = "https://images.craigslist.org/{}_300x300.jpg"
# Create your views here.
def home(request):
    return render(request, 'base.html')

def new_search(request):
    search = request.POST.get('search')
    models.Search.objects.create(search=search)

    final_url = BASE_CRAIGLIST_URL.format(quote_plus(search))
    data = requests.get(final_url, verify=False).text
    
    soup = BeautifulSoup(data, features="html.parser")
    post_listings = soup.find_all('li', {'class': 'result-row'})

    final_postings = list()
    
    for post in post_listings:
        post_title = post.find(class_='result-title').text
        post_url = post.find('a').get('href')
        if post.find(class_='result-price'):
            post_price = post.find(class_='result-price').text
        else:
            post_price ='N/A'
        if post.find(class_='result-image').get('data-ids'):
            post_image_id = post.find(class_='result-image').get('data-ids').replace("1:","").split(',')[0]
            post_image_url = BASE_CRAIGLIST_IMAGE_URL.format(post_image_id)
        else: 
            post_image_url = "https://craigslist.org/images/peace.jpg"

        final_postings.append((post_title, post_url, post_price, post_image_url))


    context = {
        'search': search,
        "final_postings" : final_postings,
    }

    price_min = request.POST.get('price_min')
    price_max = request.POST.get('price_max')
 
    return render(request, "my_app/new_search.html", context)

templates/base.html
{% load static %}

<script>
    $(document).ready(function(){
       $('select').formSelect();
   });
</script>

<html lang="en">
    
<head>
    
    <meta charset="UTF-8">
    <title>Craiglist Scraper</title>

    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" >  
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

<body>
    <nav>
        <div class="container nav-wrapper "> 
            <a href="/" class="brand-logo">Craiglist Scraper</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <h1 style="text-align: center;"> What do you want to search for on Craiglist scraper</h1>
        <div class="row">
            <div class="col s4">
                <div class="center">
                    <i class="large material-icons" style="color: #EE6E82;">flash_on</i>
                    <p>Fast Craiglist Web Scraper</p>
                    <p class="light center">Scrape away right here with amazing GUI</p> 
                </div>
            </div>
            <div class="col s4">
                <div class="center">
                    <i class="large material-icons" style="color: orange;">camera</i>
                    <p>Filter your searches</p>
                    <p class="light center">We built in functionality to filter based on price range</p> 
                </div>
            </div>
            <div class="col s4">
                <div class="center">
                    <i class="large material-icons" style="color: blue;">chrome_reader_mode</i>
                    <p>A cleaner front-end to Craiglist</p>
                    <p class="light center">We built it with ❤</p> 
                </div>
            </div>
        </div>



    <form action="{% url 'my_app:new_search' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="search" placeholder="Search">
        <input type="text" name="price_min" placeholder="Price Min">
        <input type="text" name="price_max" placeholder="Price Max">
        <button class="waves-effect waves-light btn" type="submit" name="action">Search</button>
    </form>

    {% block content %}

    {% endblock content %}
</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

templates/my_app/new_search.html
{% extends 'base.html' %}

{% block content %}

<h2 style="text-align: center;">{{ search | title }}</h2>
<div class="row">
    {% for post in final_postings %}
    <div class="col s4">
        <div class="card">
            <div class="card-image">
                <a href="{{ post.1 }}"><img src="{{ post.3 }}" alt=""></a>
            </div>
            <div class="card-content">
                <p>{{ post.0 }}</p>
            </div>
            <div class="card-action">
                <a href="{{ post.1 }}">View listing: Price {{ post.2 }}</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}